apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 703671925616.dkr.ecr.ap-south-1.amazonaws.com/backend-dotnet:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
